name: MERN CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  #  STAGE 1: Docker Images Build & Push 
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend Image Build and Push
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend:v2

      # Frontend Image Build and Push
      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend:v2

  #  STAGE 2: AWS Server Auto Deploy 
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH into AWS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/mern-task-manager-devops
            git fetch --all
            git reset --hard origin/main
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d